### ISSUE TITLE
Issue In api  call api/v1/auth/phoneNumber/authorize/

### ISSUE THREAD

**Issue by AbdurRehman91** [genitrust/woc-reference-client#3]
there is issue in api call  v1/auth/phoneNumber/authorize/ in which i am calling the api by the phone number i am registered.instead of giving me the token,the response is 
{"detail": "Unable to authorize your phone number. Probably password is invalid."}

**Comment by rgenito** [comment]
You will need the end user's Wall of Coins' password to use /api/v1/auth/{{phone number}}/authorize/ -- likewise, they will need to already have a Wall of Coins account.
